import * as crypto from "crypto";

/**
 * Parsed frontmatter from a Docusaurus markdown file.
 */
export interface Frontmatter {
  id?: string;
  title?: string;
  slug?: string;
  sidebar_position?: number;
  [key: string]: string | number | undefined;
}

/**
 * Parse YAML-style frontmatter from a markdown file.
 * Returns the metadata object and the body (content after the closing ---).
 *
 * Supports the format generated by build_docs.py:
 *   ---
 *   id: 06-6-proof-of-credibility-reputation-matching
 *   sidebar_position: 6
 *   title: "6. Proof-of-Credibility (Reputation & Matching)"
 *   slug: proof-of-credibility-reputation-matching
 *   ---
 */
export function parseFrontmatter(raw: string): {
  metadata: Frontmatter;
  body: string;
} {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) return { metadata: {}, body: raw };

  const metadata: Frontmatter = {};
  for (const line of match[1].split("\n")) {
    const colonIdx = line.indexOf(":");
    if (colonIdx === -1) continue;

    const key = line.slice(0, colonIdx).trim();
    const value = line
      .slice(colonIdx + 1)
      .trim()
      .replace(/^["']|["']$/g, ""); // Strip surrounding quotes

    // Parse numeric fields
    if (key === "sidebar_position") {
      metadata[key] = parseInt(value, 10);
    } else {
      metadata[key] = value;
    }
  }

  return { metadata, body: match[2] };
}

/**
 * Extract the numeric order prefix from a filename like "06-6-proof-of-credibility.md".
 * Returns the leading number (e.g. 6) or Infinity if no prefix is found.
 */
export function extractOrderFromFilename(filename: string): number {
  const match = filename.match(/^(\d+)-/);
  return match ? parseInt(match[1], 10) : Infinity;
}

/**
 * SHA-256 content hash for change detection.
 */
export function generateContentHash(content: string): string {
  return crypto.createHash("sha256").update(content).digest("hex");
}
