import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: "category",
      label: "Whitepaper",
      collapsible: true,
      collapsed: true,
      link: {
        type: "doc",
        id: "whitepaper/00-abstract",
      },
      items: [
        "whitepaper/01-the-vision",
        "whitepaper/02-design-goals-and-non-goals",
        "whitepaper/03-system-overview",
        "whitepaper/04-cryptographic-primitives-proof-integration",
        "whitepaper/05-trade-protocol-on-and-off-ramp",
        "whitepaper/06-proof-of-credibility-reputation-matching",
        "whitepaper/07-fraud-prevention",
        "whitepaper/08-dispute-resolution",
        "whitepaper/09-pricing-oracle-mechanics",
        "whitepaper/10-liquidity-market-design",
        "whitepaper/11-security-model",
        "whitepaper/12-privacy-model",
        "whitepaper/13-compliance-policy-positioning",
        "whitepaper/14-accessing-p2p-protocol-clients-sdks",
        "whitepaper/15-governance-upgradability",
        "whitepaper/16-token-economics",
        "whitepaper/17-disclosures-risks",
        "whitepaper/18-references",
        "whitepaper/19-appendices",
      ],
    },
    {
      type: "category",
      label: "For Investors",
      collapsible: true,
      collapsed: true,
      link: {
        type: "doc",
        id: "for-investors/start-here",
      },
      items: [
        "for-investors/investor-thesis",
        "for-investors/why-the-token-exists",
        "for-investors/token-details",
        "for-investors/token-utility",
        "for-investors/token-allocation",
        "for-investors/metadao-sale",
        "for-investors/vesting-schedules",
        "for-investors/treasury-and-token-value",
        "for-investors/staking-mechanics",
        "for-investors/token-holder-governance",
        "for-investors/progressive-decentralization",
        "for-investors/multichain-strategy",
        "for-investors/insurance",
        "for-investors/financials-and-estimates",
        "for-investors/disclosures",
        "for-investors/faq",
      ],
    },
    {
      type: "category",
      label: "For Builders",
      collapsible: true,
      collapsed: true,
      link: {
        type: "doc",
        id: "for-builders/start-here",
      },
      items: [
        "for-builders/roles-and-permissions",
        "for-builders/protocol-parameters",
        "for-builders/disputes",
        "for-builders/reputation",
        "for-builders/contract-references",
        "for-builders/fiat-to-fiat-remittance",
        "for-builders/global-currency-expansion",
        "for-builders/rollout-sequence",
        "for-builders/faq",
      ],
    },
    {
      type: "category",
      label: "For P2P Merchants",
      collapsible: true,
      collapsed: true,
      link: {
        type: "doc",
        id: "for-merchants/start-here",
      },
      items: [
        "for-merchants/merchant-readiness",
        "for-merchants/merchant-setup-flow",
        "for-merchants/handling-orders",
        "for-merchants/operational-controls",
        "for-merchants/circles-of-trust",
        "for-merchants/payment-channels-and-country-controls",
        "for-merchants/order-assignment",
        "for-merchants/disputes",
        "for-merchants/delegation-and-revenue-sharing",
        "for-merchants/insurance",
        "for-merchants/risk-and-reliability-practices",
        "for-merchants/troubleshooting",
        "for-merchants/faq",
      ],
    },
    {
      type: "category",
      label: "For Users",
      collapsible: true,
      collapsed: true,
      link: {
        type: "doc",
        id: "for-users/start-here",
      },
      items: [
        "for-users/before-you-start",
        "for-users/order-types",
        "for-users/how-to-place-an-order",
        "for-users/what-to-do-by-order-type",
        "for-users/understanding-order-states",
        "for-users/disputes-and-evidence",
        "for-users/troubleshooting",
        "for-users/faq",
      ],
    },
    {
      type: "category",
      label: "For Community",
      collapsible: true,
      collapsed: true,
      link: {
        type: "doc",
        id: "for-community/start-here",
      },
      items: [
        "for-community/cypherpunk-20-manifesto",
        "for-community/hierarchy",
        "for-community/four-tracks",
        "for-community/how-to-join",
        "for-community/weekly-updates-and-offboarding",
        "for-community/remuneration",
        "for-community/discord-structure",
        "for-community/principles",
        "for-community/faq",
      ],
    },
  ],
};

export default sidebars;
